### DISCUSSION TITLE
CSS recommendation for required fields

### DISCUSSION THREAD

**Discussion by henriquek3** [TiagoSilvaPereira/vemto-issues#221] [Ideas & Suggestions]
Increment this CSS snippet to put a red * on the field labels that are required

```css
.label-required:after {
    content: " *";
    color: red;
}
```
