### ISSUE TITLE
CSS recommendation for required fields

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-issues#219]
Increment this CSS snippet to put a red * on the field labels that are required

```css
.label-required:after {
    content: " *";
    color: red;
}
```
